# Generated by Django 5.1.6 on 2025-02-11 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('custom_name', models.CharField(blank=True, help_text='Opcjonalna nazwa własna, ułatwiająca wyszukiwanie', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Pole opcjonalne – w razie potrzeby numer seryjny', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_original', models.ImageField(help_text='Oryginalne zdjęcie', upload_to='products/photos/original/')),
                ('photo_converted', models.ImageField(blank=True, help_text='Zdjęcie zoptymalizowane do rozdzielczości web (max 1080px)', null=True, upload_to='products/photos/converted/')),
                ('state', models.CharField(choices=[('magazyn', 'Magazyn'), ('wyjezd', 'Na wyjezdzie')], default='magazyn', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Komplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(blank=True, related_name='komplety', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_start', models.DateField(help_text='Data rozpoczęcia wypożyczenia')),
                ('borrow_end', models.DateField(help_text='Data zakończenia wypożyczenia')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.product')),
            ],
        ),
    ]
