# Generated by Django 5.1.6 on 2025-02-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_converted',
            field=models.ImageField(blank=True, help_text='Przekonwertowane zdjęcie (WebP) – nie wyświetlane w UI', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Pole opcjonalne – numer seryjny', max_length=100, null=True),
        ),
    ]
