# Generated by Django 5.1.6 on 2025-02-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_photo_converted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='borrow_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='borrow_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Opcjonalna nazwa własna', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_converted',
            field=models.ImageField(blank=True, help_text='Przekonwertowane zdjęcie (WebP)', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_original',
            field=models.ImageField(blank=True, help_text='Oryginalne zdjęcie produktu (opcjonalne)', null=True, upload_to='products/photos/original/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Opcjonalny numer seryjny', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('magazyn', 'Magazyn'), ('wyjezd', 'Na wyjeździe')], default='magazyn', max_length=10),
        ),
    ]
