# Generated by Django 5.1.6 on 2025-02-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_borrowingrecord_borrow_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('reserved', 'Zarezerwowane'), ('in_progress', 'W toku'), ('completed', 'Zakończone'), ('canceled', 'Anulowane')], default='reserved', max_length=20)),
                ('reservation_date', models.DateField(help_text='Data rezerwacji (złożenia zamówienia)')),
                ('pickup_date', models.DateField(help_text='Data odbioru')),
                ('return_date', models.DateField(help_text='Data zwrotu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
