# Generated by Django 5.1.6 on 2025-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, help_text='Waga (w kg)', null=True),
        ),
    ]
