# Generated by Django 5.1.6 on 2025-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, help_text='Waga (w kg)', max_length=4, null=True),
        ),
    ]
