# Generated by Django 5.1.6 on 2025-02-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Opis - jeśli posiada inne komponenty, lokalizacja', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, help_text='Waga w kilogramach', max_length=4, null=True),
        ),
    ]
