# Generated by Django 5.1.6 on 2025-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_borrowhistory_delete_borrowingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.TextField(blank=True, help_text='Kod EAN', max_length=13, null=True),
        ),
    ]
