# Generated by Django 5.1.6 on 2025-02-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_komplet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komplet',
            options={'verbose_name_plural': 'Zestawy'},
        ),
    ]
